---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsync: https://github.com/simp/pupmod-simp-rsync
    selinux_core:
      repo: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd: https://github.com/simp/puppet-systemd
