---
HOSTS:
  el7-server:
    roles:
    - server
    - default
    - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el7-ldap:
    roles:
    - ldap
    - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el8-server:
    roles:
    - server
    - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  el8-ldap:
    roles:
    - 389ds
    - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  synced_folder: disabled
  type: aio
  vagrant_memsize: 256
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
