<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7-server:
    roles:
     - server
     - default
     - master
     - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
  el7-ldap:
    roles:
      - ldap
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      simp:
        baseurl: https://packagecloud.io/simp-project/6_X_Dependencies/el/7/$basearch
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
#  el7:
#    roles:
#      - client
#    platform: el-7-x86_64
#    box: centos/7
#    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  synced_folder : disabled
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
